# Generated by Django 5.2.13 on 2026-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomec', models.CharField(max_length=100)),
                ('idadec', models.IntegerField()),
                ('raca', models.CharField(max_length=50, null=True)),
                ('doenca', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
