# Generated by Django 5.2.15 on 2026-06-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
